config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Users', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->connect('uniqueRetailerEmail', ['controller' => 'Retailer', 'action' => 'uniqueRetailerEmail']);
    $routes->connect('uniqueRetailerMobile', ['controller' => 'Retailer', 'action' => 'uniqueRetailerMobile']);
    $routes->connect('uniqueUserMobile', ['controller' => 'Users', 'action' => 'uniqueUserMobile']);
    $routes->connect('enableDate', ['controller' => 'Category', 'action' => 'getEnableDate']);
    $routes->connect('cod', ['controller' => 'Cod', 'action' => 'index']);
    $routes->connect('cod', ['controller' => 'Cod', 'action' => 'index']);
    $routes->connect('subcategory', ['controller' => 'SubCategory', 'action' => 'index']);
    $routes->connect('subcategory/add', ['controller' => 'SubCategory', 'action' => 'add']);
    $routes->connect('subcategory/edit/*', ['controller' => 'SubCategory', 'action' => 'edit']);
    $routes->connect('enableSubCategory', ['controller' => 'SubCategory', 'action' => 'getEnableSubCategory']);
    $routes->connect('offer', ['controller' => 'Offer', 'action' => 'index']);
    $routes->connect('welcomeoffer', ['controller' => 'WelcomeOffer', 'action' => 'index']);
    $routes->connect('welcomeoffer/add', ['controller' => 'WelcomeOffer', 'action' => 'add']);
    $routes->connect('welcomeoffer/edit/*', ['controller' => 'WelcomeOffer', 'action' => 'edit']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});
Router::scope('/api/', function (RouteBuilder $routes) {
    $routes->setExtensions(['json']);
    $routes->connect('admin/login', ['controller' => 'ApiUsers', 'action' => 'authenticateUser']);

    //API User
    $routes->connect('admin', ['controller' => 'ApiUsers', 'action' => 'index']);
    $routes->connect('admin/*', ['controller' => 'ApiUsers', 'action' => 'userView']);
    $routes->connect('admin/add', ['controller' => 'ApiUsers', 'action' => 'userAdd']);
    $routes->connect('admin/update/*', ['controller' => 'ApiUsers', 'action' => 'userEdit']);
    $routes->connect('admin/delete/*', ['controller' => 'ApiUsers', 'action' => 'userDelete']);

    //API Shop
    $routes->connect('login', ['controller' => 'ApiShop', 'action' => 'authenticateUser']);
    $routes->connect('user', ['controller' => 'ApiShop', 'action' => 'index']);
    $routes->connect('user/info/*', ['controller' => 'ApiShop', 'action' => 'userInfo']);
    $routes->connect('user/*', ['controller' => 'ApiShop', 'action' => 'userView']);
    $routes->connect('user/add', ['controller' => 'ApiShop', 'action' => 'userAdd']);
    $routes->connect('user/update/*', ['controller' => 'ApiShop', 'action' => 'userEdit']);
    $routes->connect('user/delete/*', ['controller' => 'ApiShop', 'action' => 'userDelete']);

    //API product
    $routes->connect('product', ['controller' => 'ApiProduct', 'action' => 'index']);
    $routes->connect('product/*', ['controller' => 'ApiProduct', 'action' => 'productView']);
    $routes->connect('product/add', ['controller' => 'ApiProduct', 'action' => 'productAdd']);
    $routes->connect('product/update/*', ['controller' => 'ApiProduct', 'action' => 'productEdit']);
    $routes->connect('product/delete/*', ['controller' => 'ApiProduct', 'action' => 'productDelete']);
    $routes->connect('promotions/*', ['controller' => 'ApiProduct', 'action' => 'promotion']);
    $routes->connect('cart/user/*', ['controller' => 'ApiProduct', 'action' => 'cartUser']);
    $routes->connect('cart/add', ['controller' => 'ApiProduct', 'action' => 'cartAdd']);
    $routes->connect('cart/update', ['controller' => 'ApiProduct', 'action' => 'cartUpdate']);
    $routes->connect('cart/delete', ['controller' => 'ApiProduct', 'action' => 'cartDelete']);

    //API Payment
    $routes->connect('retailer-payment', ['controller' => 'ApiProduct', 'action' => 'payment']);
    $routes->connect('refunds', ['controller' => 'ApiProduct', 'action' => 'refunds']);
    $routes->connect('checkout', ['controller' => 'ApiProduct', 'action' => 'checkout']);
    $routes->connect('cards', ['controller' => 'ApiProduct', 'action' => 'cards']);
    $routes->connect('transfers', ['controller' => 'ApiProduct', 'action' => 'transfers']);
    $routes->connect('payments/*', ['controller' => 'ApiProduct', 'action' => 'paymentList']);
    
    //API category
    $routes->connect('category', ['controller' => 'ApiCategorys', 'action' => 'index']);
    $routes->connect('category/*', ['controller' => 'ApiCategorys', 'action' => 'categoryView']);
    $routes->connect('category/add', ['controller' => 'ApiCategorys', 'action' => 'categoryAdd']);
    $routes->connect('category/update/*', ['controller' => 'ApiCategorys', 'action' => 'categoryEdit']);
    $routes->connect('category/delete/*', ['controller' => 'ApiCategorys', 'action' => 'categoryDelete']);
});

src/Model/Table/SubCategoryTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Category Model
 *
 * @method \App\Model\Entity\Category get($primaryKey, $options = [])
 * @method \App\Model\Entity\Category newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Category[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Category|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Category|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Category patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Category[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Category findOrCreate($search, callable $callback = null, $options = [])
 */
class SubCategoryTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('tbl_sub_categories');
        $this->setDisplayField('sub_category_id');
        $this->setPrimaryKey('sub_category_id');

        $this->addBehavior('Timestamp', [
            'events' => [
                'Model.beforeSave' => [
                    'created_on' => 'new',
                    'updated_on' => 'always',
                ],
            ]
        ]);

         $this->belongsTo('tbl_categories', [
            'foreignKey' => 'category_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('sub_category_id')
            ->allowEmpty('sub_category_id', 'create');
        $validator
            ->scalar('category_id')
            ->requirePresence('category_id', 'create')
            ->notEmpty('category_id');
        $validator
            ->scalar('sub_category_name')
            ->maxLength('sub_category_name', 50)
            ->requirePresence('sub_category_name', 'create')
            ->notEmpty('sub_category_name');

        $validator
            ->scalar('image')
            ->maxLength('image', 150)
            ->allowEmpty('image');

        return $validator;
    }

    public function getCat() {
        $query = $this->find('all')->select(['sub_category_id','sub_category_name'])->toArray();
        return $query;
    }

    public function getCatInfo() {
        $query = $this->find('all')->select(['sub_category_id','category_id','sub_category_name'])->toArray();
        $categories = array();
        if (!empty($query)) {
            foreach ($query as $category) {
                $cat['sub_category_id'] = $category->sub_category_id;
                $cat['sub_category_name'] = $category->sub_category_name;
                $cat['category_id'] = $category->category_id;
                $categories[] = $cat;
            }
        }
        return $categories;
    }
}

src/Controller/SubCategoryController.php
<?php
namespace App\Controller;

Use App\Controller\AppController;

class SubCategoryController extends AppController {
    public function initialize()
    {
        parent::initialize();
        $this->loadModel('Category');
        $this->loadModel('SubCategory');
    }
	public function index() {
		$searchParams = $this->request->data();
        $conditions = array();

        if(!empty($searchParams)) {
            if(!empty($searchParams['name'])) {
                $conditions['sub_category_name like'] = trim("%".$searchParams['name']."%", " ");
            }
             if(!empty($searchParams['category_name'])) {
                $conditions['category_name like'] = trim("%".$searchParams['category_name']."%", " ");
            }
            $this->paginate = ['conditions' => $conditions];
        }

		 //$subcategory = $this->paginate($this->SubCategory);
        $subcategory = $this->SubCategory->find('all', ['contain' => 'tbl_categories'])->where($conditions)->toArray();
       // print_r($subcategory);
		$this->set(compact('subcategory', 'searchParams'));
	}
    public function add() {
       $category = $this->Category->getCat();
       $subcategory = $this->SubCategory->newEntity();
        if($this->request->is('post')) {
            $data = $this->request->data();
            if(!empty($data["image"]["name"])) {
                $file = $data["image"];
                $ext = substr(strtolower(strrchr($file['name'], '.')), 1);
                $extArr = array('jpg', 'jpeg', 'gif', 'png');
                $name = time().'-'.$file['name'];
                $upload_path = WWW_ROOT.'img/subcategory/';
                if(in_array($ext, $extArr)) {
                    move_uploaded_file($file['tmp_name'], $upload_path.$name);
                    $data['image'] = $name;
                }
            }
            $subcategories = $this->SubCategory->find()->select()->where(['sub_category_name'=>$data['sub_category_name']])->toArray();
            if (!empty($subcategories)) {
                $this->Flash->error(__("Sub Category name already used."));
            } else {
                $subcategory = $this->SubCategory->patchEntity($subcategory, $data);
                if($this->SubCategory->save($subcategory)) {
                    $this->Flash->success(__("Sub category has been saved"));
                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error(__("Category Name is required."));
            }
        }
        $this->set(compact('subcategory','category'));
    }
    public function edit($id = null) {
        $category = $this->Category->getCat();
        $subcategory = $this->SubCategory->get($id);
        if ($this->request->is(['patch', 'post', 'put'])) {
            if(!empty($this->request->getData())) {
                $data = $this->request->getData();
                if(!empty($data["image"]["name"])) {
                    $file = $data["image"];
                    $ext = substr(strtolower(strrchr($file['name'], '.')), 1);
                    $extArr = array('jpg', 'jpeg', 'gif', 'png');
                    $name = time().'-'.$file['name'];
                    $upload_path = WWW_ROOT.'img/subcategory/';
                    if(in_array($ext, $extArr)) {
                        move_uploaded_file($file['tmp_name'], $upload_path.$name);
                        $data['image'] = $name;
                    }
                }
            }
            $subcategory = $this->SubCategory->patchEntity($subcategory, $data);
            if ($this->SubCategory->save($subcategory)) {
                $this->Flash->success(__('The sub category has been updated.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('Category Name is required.'));
        }
        $this->set(compact('subcategory','category'));
    }

    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $subcategory = $this->SubCategory->get($id);
        if ($this->SubCategory->delete($subcategory)) {
            $this->Flash->success(__('The sub category has been deleted.'));
        } else {
            $this->Flash->error(__('The sub category could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
    public function getEnableSubCategory()
    {
        if ($this->request->is(['post'])) {
            $category = $this->request->getData();
            $catId = $category["category_id"];
            $subcategory = $this->SubCategory->find()->select()->where(['SubCategory.category_id'=>$catId])->toArray();
            $ArrySubCate=array();
            $i=0;
            if (count($subcategory)>0) {
                foreach ($subcategory as $subcategoryDetails){
                    $ArrySubCate[$i]["sub_cate_id"]=$subcategoryDetails->sub_category_id;
                    $ArrySubCate[$i]["sub_cate_name"]=$subcategoryDetails->sub_category_name;
                    $i++;
                }
                $result="success##^^##".json_encode($ArrySubCate);
            } else{
                $result="failure"; 
            }
        }
        die($result);
    }
}
?>

src/Template/SubCategory/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Setting $setting
 */
?>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption icon-sprite"><i class="icon-drivers"></i><span class="caption-subject bold"> Add Sub Category</span></div>
        <div class="actions"><a class="btn btn-default btn-sm" href="<?php echo BASE_URL ?>/subcategory">Back</a></div>
    </div>
        <div class="portlet-body">
            <div class="form-horizontal">
                <?= $this->Form->create($subcategory,array('enctype'=>'multipart/form-data', 'class'=>'subcategory')) ?>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="type">Category Name<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <?php if(!empty($category)) { ?>
                                <select name="category_id" class="form-control">
                                        <option value="">-- Select --</option>
                                        <?php foreach ($category as $categorys) { ?>
                                            <option value="<?php echo $categorys['category_id']?>"><?php echo $categorys['category_id'].' - '.$categorys['category_name']; ?></option>
                                        <?php } ?>
                                </select>
                            <?php } else { ?>
                                <select name="" class="form-control">
                                    <option value="">Please create category</option>
                                </select>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="type">Sub Category Name<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <input class="name form-control" type="text" name="sub_category_name" placeholder="Sub Category Name" value=""/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="type">Image<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <input class="value form-control" type="file" name="image" value=""/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-5">
                            <button class="btn btn-primary submit-form customsavebtn" type="submit"><i class="fa fa-save"></i> Save</button>
                            <a class="btn btn-primary cancel-btn custombackbtn" title="Go back to listing page" href="<?php echo BASE_URL;?>/subcategory"><i class="fa fa-angle-left"></i> Cancel</a>
                        </div>
                    </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</div>

src/Template/SubCategory/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Setting $setting
 */
?>
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption icon-sprite"><i class="icon-drivers"></i><span class="caption-subject bold"> Edit Sub Category</span></div>
        <div class="actions"><a class="btn btn-default btn-sm" href="<?php echo BASE_URL ?>/subcategory">Back</a></div>
    </div>
        <div class="portlet-body editing">
            <div class="form-horizontal">
                <?= $this->Form->create($subcategory,array('enctype'=>'multipart/form-data', 'class'=>'subcategory')) ?>
                   <div class="form-group">
                        <label class="control-label col-md-3" for="type">Category Name<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <?php if(!empty($category)) { ?>
                                <select name="category_id" class="form-control">
                                        <option value="">-- Select --</option>
                                        <?php foreach ($category as $categorys) { 
                                            $select=($categorys['category_id']==$subcategory->category_id)?"Selected":"";
                                            ?>
                                            
                                            <option value="<?php echo $categorys['category_id']?>" <?php echo $select?>><?php echo $categorys['category_id'].' - '.$categorys['category_name']; ?></option>
                                        <?php } ?>
                                </select>
                            <?php } else { ?>
                                <select name="" class="form-control">
                                    <option value="">Please create category</option>
                                </select>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="type">Sub Category Name<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <input class="name form-control" type="text" name="sub_category_name" placeholder="Sub Category Name" value="<?= $subcategory->sub_category_name ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3" for="type">Image<span class="required"> *</span></label>
                        <div class="col-md-5">
                            <img title="<?= $subcategory->image ?>" alt="<?= $subcategory->image ?>" class="image_prod" src="<?= BASE_URL.'/img/subcategory/'.$subcategory->image ?>">
                            <span class="fa fa-times"></span>
                            <input class="hidden img_upload form-control" type="text" name="image" placeholder="Image Url" value="<?php echo $subcategory['image']?>"/>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3"></div>
                        <div class="col-md-5">
                            <button class="btn btn-primary submit-form customsavebtn" type="submit"><i class="fa fa-save"></i> Update</button>
                            <a class="btn btn-primary cancel-btn custombackbtn" title="Go back to listing page" href="<?php echo BASE_URL ?>/subcategory"><i class="fa fa-angle-left"></i> Cancel</a>
                        </div>
                    </div>
                <?= $this->Form->end() ?>
            </div>
        </div>
    </div>
</div>

src/Template/SubCategory/index.ctp
<div class="portlet box green driver-list">
    <div class="portlet-title">
        <div class="caption icon-sprite"><i class="icon-drivers"></i><span class="caption-subject bold"> Sub Category</span></div>
        <div class="actions"><a class="btn green btn-sm customaddbtn" title="Add Subcategory" href="<?php echo BASE_URL;?>/subcategory/add">Add <i class="fa fa-plus"></i></a></div>
    </div>
    <div class="portlet-body listing">
        <div class="row">
            <?= $this->Form->create("",['type'=>'post']) ?>
                <div class="col-md-3"><input class="form-control" type="text" placeholder="Category Name" name="category_name" value="<?php echo !empty($searchParams) ? $searchParams['category_name'] : '' ?>"></div>
                <div class="col-md-3"><input class="form-control" type="text" placeholder="Sub Category Name" name="name" value="<?php echo !empty($searchParams) ? $searchParams['name'] : '' ?>"></div>
                <div class="col-md-3"><button class="btn btn-success customsearchbtn" type="submit" title="Search"><i class="fa fa-search"></i> Search</button><a class="btn btn-success customresetbtn" title="Reset"  href="<?php echo BASE_URL;?>/subcategory"><i class="fa fa-undo"></i> Reset</a></div>
            <?= $this->Form->end() ?>
        </div>
        <table class="table table-striped table-bordered table-hover table-checkable order-column" id="driver">
            <thead>
                <tr>
                    <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('category name') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('Sub category name') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('image') ?></th>
                    <th scope="col" class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($subcategory as $category): ?>
                <tr>
                    <td><?= $this->Number->format($category->sub_category_id) ?></td>
                    <td><?= h($category->tbl_category->category_name) ?></td>
                    <td><?= h($category->sub_category_name) ?></td>
                    <td><img title="<?= $category->image ?>" alt="<?= $category->image ?>" class="image_prod" src="<?= BASE_URL.'/img/subcategory/'.$category->image ?>">
                    </td>
                    
                    <td class="actions">
                        <?= $this->Html->link('<i class="fa fa-edit"></i> ' .__('Edit'), ['action' => 'edit', $category->sub_category_id],['escape' => false, 'type'=>'button','class'=>'btn grey-cascade btn-xs customeditbtn','title' => __('Edit')]) ?>
                        <?= $this->Form->postLink('<i class="fa fa-trash"></i> '.__('Delete'), ['action' => 'delete', $category->sub_category_id], ['escape' => false,'confirm' => __('Are you sure you want to delete # {0}?', $category->sub_category_id),'class'=>'btn grey-cascade btn-xs customdeletebtn','title' => __('Delete')]) ?>
                        <a data-toggle="modal" data-value="view" title="View" data-target="#view_detail" type="button" class="btn grey-cascade view_detail btn-xs customviewbtn"><i class="fa fa-eye"></i> View</a>
                        <div class="hidden row_detail portlet box green">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title"><b><?= h($category->sub_category_name) ?></b></h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-horizontal">
                                            <table class=" table vertical-table table-bordered">
                                                <tr>
                                                    <th scope="row"><?= __('Id') ?></th>
                                                    <td><?= $this->Number->format($category->sub_category_id) ?></td>
                                                </tr>
                                                <tr>
                                                    <th scope="row"><?= __('Category Name') ?></th>
                                                    <td><?= h($category->tbl_category->category_name) ?></td>
                                                </tr>
                                                <tr>
                                                    <th scope="row"><?= __('Sub Category Name') ?></th>
                                                    <td><?= h($category->sub_category_name) ?></td>
                                                </tr>
                                                <tr>
                                                    <th scope="row"><?= __('Image') ?></th>
                                                    <td><img title="<?= $category->image ?>" alt="<?= $category->image ?>" class="image_prod" src="<?= BASE_URL.'/img/subcategory/'.$category->image ?>"></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <!-- <div class="paginator">
            <ul class="pagination">
                <?= $this->Paginator->first('<< ' . __('first')) ?>
                <?= $this->Paginator->prev('< ' . __('previous')) ?>
                <?= $this->Paginator->numbers() ?>
                <?= $this->Paginator->next(__('next') . ' >') ?>
                <?= $this->Paginator->last(__('last') . ' >>') ?>
            </ul>
        </div> -->
    </div>
</div>
<div class="modal fade in" id="view_detail" tabindex="-1" role="basic" aria-hidden="true">
</div>